[build]
  base = "."
  command = "npm run build"
  functions = "functions"

[dev]
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true
